# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_profile', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
